### PR TITLE
try to solve #150 using vim.register_keystroke_callback

### PR DESCRIPTION
**Pull request by zeertzjq**
Works for inserted characters and cursor movement. May not work for keys that cannot be pressed twice, or inserting text in multiple lines (as `_correct` cannot reverse them).

The `<c-z>` is added because of <https://github.com/neovim/neovim/pull/15538>. If the user has `'insertmode'` set, suspending again is not the desired behavior either.

I think `<c-e>`, `<c-y>` and `<c-z>` can be set to global constants to avoid calling api every time, but IDK how to do that in coq. (Maybe using `with Atomic()`?)

### CODE REVIEW

**Comment by zeertzjq** [comment]
Maybe this should be made optional because the API may change in future (<https://github.com/neovim/neovim/pull/15460>), but I cannot think of a good option name.

**Comment by zeertzjq** [comment]
Maybe I am complicating the problem.

**Comment by ms-jpq** [comment]
honestly yeah, im not confident about doing it this way either, seems like an edge case trap.

my ideal approach would be to store the [changes here](https://github.com/ms-jpq/coq_nvim/blob/7d3a2eaed1fbc09ca24405ff04a6d71558640b87/coq/server/edit.py#L345) and reconcile it with the edit, and apply the change afterwards with an `EditInstruction`.

Now that is like probably the best all around solution, but at the same time, super super annoying to get it right, thats why I didn't do it, there are lower hanging fruits.

**Comment by ms-jpq** [comment]
like even doing it this way its like there can be edge cases where it doesn't work, but can't be worse than what we have now.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/189

**Comment by ms-jpq** [comment]
turns out it was like 5 lines of change, lol, i overestimated how hard this was gonna be and put it off for like 4 days

**Pull request closed without merging**
