### PR TITLE
coq.vim -> coq.lua

### PR DESCRIPTION
**Pull request by mcchrish**
Ever since this PR https://github.com/neovim/neovim/pull/14686 lua files are source just like vim files.

Will probably save 1 nanosecond.

### CODE REVIEW

**Comment by ms-jpq** [comment]
haha, ive thought about doing this, but is it really compatible with all the plugin mangers though?

i am a bit concerned that some ancient bespoke thingy will just break.

**Comment by mcchrish** [comment]
As far as I know, vim-plug (vundle too?) simply tweak some rtp while newer ones like packer/paq uses the builtin package manager (packadd etc). Both are compatible with this change.
Other plugin managers, if they're doing something funny I'm not really sure.

**Comment by ms-jpq** [comment]
yeah.. because I wrote my own special snowflake plugin manager lol, so like there are people out there who do stuff like that.

im sorry but honestly, i see this as like a potential wtf moment for people if their stuff breaks randomly, and I don't want to risk that.

if I like deprecated some other feature, or something `coq.nvim` will actively try to warn people about it, or at least throw a reasonable error.

this one is just like zero feedback.

anyways i feel bad closing this PR, but yeah, sorry

**Comment by ms-jpq** [comment]
I mean i would 100% merge it if it was before `coq.nvim` was released.

**Comment by mcchrish** [comment]
No worries, it's quite understandable 👍

**Comment by ms-jpq** [comment]
also this is kinda off topic, but you really look like a friend i knew in high school, he was a pretty awesome guy but we lost touch.

**Comment by mcchrish** [comment]
Haha, interesting..
Meahwhile, you look to be coding 24/7 based on the recent commit history. You need to chill haha

**Comment by ms-jpq** [comment]
well, check out the [new snippets!](https://github.com/ms-jpq/coq_nvim/blob/coq/docs/SNIPS.md)

they are awesome :D

**Comment by mcchrish** [comment]
Yeah, I'm gonna check it soon. Gonna port my custom snippets to this.
And so glad you choose the standard LSP grammar, I thought you would write a new snippet template style just for coq haha

**Comment by ms-jpq** [comment]
what, why would i do that!

i have enough code already!

plus the LSP snippet and most viml snippets are similar enough to be almost compatible :D

**Comment by mcchrish** [comment]
_"Insert famous xkcd comic about standards here"_

> i have enough code already!

Need more sqlite instances! Haha just kidding. Thanks for making a great plugin!

**Comment by mcchrish** [comment]
I'm in the process of converting my snippets to coq. One thing I miss though from coc is that I can expand the snippet using the abbr.
For example I type `for` then pressed `<c-l>` (the trigger key) it will immediately expands the for-loop snippet. Or type `forin` it expands to for in loop etc.

Another is that coq doesn't complete abbr. For example, my abbr for "console.log" is `cl`, but when I type `cl` the snippet does not show up:

Screen Shot 2021-09-07 at 5 37 24 PM

Screen Shot 2021-09-07 at 5 39 50 PM

I'll probably create a separate issue for this.

**Comment by ms-jpq** [comment]
abbr -> label only

alias -> match

i should make that clear in the docs

**Comment by mcchrish** [comment]
Got it, it works now 👍

**Comment by ms-jpq** [comment]
not sure what you mean by the other thingy, but yeah im gonna slep so i guess please send me a gif or something of the thingy you want, my brain is at 0% right now (its 3am)

**Comment by mcchrish** [comment]
The gif as requested https://github.com/ms-jpq/coq_nvim/issues/232

**Pull request closed without merging**
