### PR TITLE
Implement all of VS code variables in snippets

### PR DESCRIPTION
**Pull request by dnaaun**
Hey @ms-jpq , I thought it would be a good idea to implement [VS Code's snippet variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) (which are a superset of the LSP specification's). I noticed only after I finished that [you don't have the bandwidth  to maintain a superset of the LSP snippet grammar.](https://github.com/ms-jpq/coq_nvim/issues/247#issuecomment-915526512) . Arguably, this PR is not a change in the grammar 😆 . But yeah, it's totally cool if this is beyond the scope of the project, since there's so many moving parts already.

PS: In the unlikely case that you are planning on implementing arbitrary code execution during snippet expansion (like [LuaSnip](https://github.com/L3MON4D3/LuaSnip/blob/ccf8d5da2370877ccf7b3ea164d0530ff1f59a87/doc/luasnip.txt#L188), or [UltiSnips](https://github.com/SirVer/ultisnips/blob/53e1921e3ef015ef658e540c0aa9c4835f9c18a6/doc/UltiSnips.txt#L820)) at some point, I would imagine that this PR shouldn't get merged since all the variables are basically python one liners behind the scenes.

### CODE REVIEW

**Comment by dnaaun** [comment]
Welp, I just realized that implementing an [nvim-cmp bridge](https://github.com/ms-jpq/coq_nvim/issues/278#issuecomment-922065054) would entail implementing arbitrary code execution (since arbitrary code can be placed in `function source:complete`, right?). So I think that really decreases the value of this PR ...

**Comment by ms-jpq** [comment]
humm since I am touching grass this weekend I will not be merging it in until a bit next week, sorry.

and about the arbitrary code execution part, dont worry, LSP allows you to [send commands](https://microsoft.github.io/language-server-protocol/specification#command), I didn't implement it yet because I wasn't sure wtf the spec meant, but I will add it in for sure 👍

**Comment by dnaaun** [comment]
> touching grass

Glad to hear you'll be getting some offline time, you certainly deserve it!🥇🎖️🏅

> LSP allows you to send commands

I believe LSP commands are not for arbitrary code execution, I think they are for funcitonalities that specific LSPs implement that are not deemed general enough to deserve their own endpoint like `textDocument/formatting`. For example, Pyright [implements commands to organize imports, create type stubs, and so on](https://github.com/microsoft/pyright/blob/7bb059ecbab5c0c446d4dcf5376fc5ce8bd8cd26/packages/pyright-internal/src/commands/commands.ts). It looks like the metals LSP [also uses LSP commands to do a bunch of metals-specific things](https://github.com/scalameta/nvim-metals/blob/d53982632b7da48a810f70c2ebccca5d450f92f5/lua/metals.lua#L18).

I don't think `workspace/executeCommand` is used for arbitrary code execution at all. In fact, I don't see why `coq` would have to deal with it, since completion has it's own dedicated LSP endpoint. But, this is all pseudo-expertise from a (neo)vimmer whose only qualification for saying such things is that he spent considerable time making sure he has as many IDE features in neovim as possible, so I may be very wrong.

**Comment by ms-jpq** [comment]
i will merge this into dev soon and work on it,

there is one thing, it seems that you had modified your local copy of `pynvim_pp`, i did not get a fork notification, so I am not sure what you did, so I will just write my own `pynvim_pp.comment`

**Comment by ms-jpq** [comment]
@davidatbu, it's a pretty easy thing tbh, just need to implement a `exec` property on top of the existing `{ name, fn }` on `COQsources`. such that `exec` will execute arbitrary commands, if passed the expected parameters.

anyways its a bunch of work so i will worry about it later, i have some family stuff this week so my time will be limited.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq_nvim/pull/290 gucci

**Comment by dnaaun** [comment]
> there is one thing, it seems that you had modified your local copy of pynvim_pp, i did not get a fork notification, so I am not sure what you did, so I will just write my own pynvim_pp.comment

I'm an idiot. I forgot to push my changes in that repo. [Here's the PR](https://github.com/ms-jpq/pynvim_pp/pull/2) in pynvim_pp.

> @davidatbu, it's a pretty easy thing tbh, just need to implement a exec property on top of the existing { name, fn } on COQsources. such that exec will execute arbitrary commands, if passed the expected parameters.

Yes! I hadn't looked into the custom sources before I ranted on this PR about arbitrary code execution. Custom sources would definitely allow arbitrary code execution.

**Comment by ms-jpq** [comment]
yeah thats a-ok :), because the user should expect arbitrary code when using lua plugins, that should not be unexpected.

the reason I never allowed the snippet to do so was because I think having snippets execute code is just not smort,

**Comment by dnaaun** [comment]
> the reason I never allowed the snippet to do so was because I think having snippets execute code is just not smort,

I totally agree. I once went crazy with UltiSnips and code execution, but it really slowed everything down. 

I have a question about the `CLIPBOARD` VSCode variable. I think the calls to `getreg()` should be changed to `getreg("+")` (ie, get the value in the "+" register, which is the system clipboard). Otherwise, `getreg()` gets the value of the default register `"`, which is set whenever you delete or yank anything.† 

The calls I am talking about are here:

https://github.com/ms-jpq/coq_nvim/blob/be669824e121f6fa71ab5a7d848125f94845f677/coq/server/registrants/user_snippets.py#L129

and here:
 
https://github.com/ms-jpq/coq_nvim/blob/be669824e121f6fa71ab5a7d848125f94845f677/coq/server/edit.py#L356

--------

† `getreg()` will switch to using the `+` and `*` register if the options `clipboard=unnamed` or `clipboard=unnamedplus` are set, respectively.  But I don't think we should rely on the user setting those options.

**Comment by ms-jpq** [comment]
i was hoping the users would set those options, but I think you are right in this case. alright ill add it next PR

**Pull request merged**
