### PR TITLE
Do not move cursor at all if user has moved cursor out of inserted text; allow triggering autocompletion if user has inserted text

### PR DESCRIPTION
**Pull request by zeertzjq**
If user has moved cursor out of inserted text, moving the cursor back to the end of the inserted text may not be the best behavior. Instead, a better behavior may be not moving the cursor at all.

For example, [nvim-autopairs](https://github.com/windwp/nvim-autopairs) moves cursor to the right by one character while not inserting anything if `}` is pressed and there is already a `}` after cursor.  In this case, the inserted text is an empty string, and cursor is out of inserted text. The expected behavior here should be still keeping the cursor after the `}`.

### CODE REVIEW

**Comment by zeertzjq** [comment]
Wait a minute

**Comment by zeertzjq** [comment]
Also, maybe returning `p_col` instead of `n_col` from `edit()` is more reasonable. For example, in Python, if the user autocompletes a module name and presses `.` to accept the completion:
- if `edit()` returns `n_col`, there is not autocompletion after the `.`, the user has to trigger it manually
- if `edit()` returns `p_col`, there is autocompletion after the `.`

**Comment by zeertzjq** [comment]
> Also, maybe returning `p_col` instead of `n_col` from `edit()` is more reasonable. For example, in Python, if the user autocompletes a module name and presses `.` to accept the completion:
> 
>     * if `edit()` returns `n_col`, there is not autocompletion after the `.`, the user has to trigger it manually
> 
>     * if `edit()` returns `p_col`, there is autocompletion after the `.`

I just renamed `p_col` to `n_col`.

**Comment by ms-jpq** [comment]
thank you!

i will take a look at this tomorrow morning, my brain is at 20% right now, been busy lately

**Pull request merged**
