### PR TITLE
Fix custom source crash

### PR DESCRIPTION
**Pull request by Mte90**
Ref: https://github.com/ms-jpq/coq_nvim/issues/358

### CODE REVIEW

**Comment by Mte90** [comment]
any hope for this? @ms-jpq

**Comment by Mte90** [comment]
ping @ms-jpq

**Comment by Mte90** [comment]
ping @ms-jpq ....

**Comment by ms-jpq** [comment]
sry, been super burnt out just dreaded chcking out emails and shit. im back now tho

**Comment by Mte90** [comment]
Thanks!

I saw just commits in the repository so I was thinking that you was missing the notification and I just started to send multiple :-)

**Pull request merged**
