### PR TITLE
ci.yml: Add codespell to discover typos

### LINKED ISSUE #59: Is istance vs. instance an intentional choice?
codespell - -ignore-words-list="thats,wit" --skip="\*.po,\*.yml"
```
./coq_nvim/coq/server/reviewer.py:55: istance ==> instance
./coq_nvim/coq/server/trans.py:113: istance ==> instance
./coq_nvim/coq/shared/runtime.py:48: istance ==> instance
./coq_nvim/coq/shared/types.py:31: Trigged ==> Triggered
./coq_nvim/coq/shared/types.py:33: Trigged ==> Triggered
```

### PR DESCRIPTION
**Pull request by cclauss**
Fixes: #59

https://pypi.org/project/codespell

### CODE REVIEW

**Comment by ms-jpq** [comment]
hahahaha, god damn

**Comment by ms-jpq** [comment]
inb4 i get flagged by 20 billion typos

**Comment by cclauss** [comment]
Now machines can find them so that people don't have to. ;-)

**Comment by ms-jpq** [comment]
omg the CI passed without complaining, wow, I guess i am not a total failure after all

was not expecting it to pass the first go

**Comment by cclauss** [comment]
I put in the magic `--ignore-words-list` so that it would pass.  Let's see what it catches in the future.

**Pull request merged**
